[package]
name = "rustyc_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyc_ast = { path = "../rustyc_ast" }
rustyc_diagnostics = { path = "../rustyc_diagnostics" }
rustyc_span = { path = "../rustyc_span" }
rustyc_token = { path = "../rustyc_token" }
