[package]
name = "rustyc_mir_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyc_diagnostics = { path = "../rustyc_diagnostics" }
rustyc_hir = { path = "../rustyc_hir" }
rustyc_hir_walker = { path = "../rustyc_hir_walker" }
rustyc_mir = { path = "../rustyc_mir" }
rustyc_ty = { path = "../rustyc_ty" }
